### ISSUE TITLE
etcd URL in kube-apiserver

### ISSUE THREAD

**Issue by jhvhs** [cloudfoundry-incubator/kubo-release#197] opened 2018-04-23 11:47 UTC
Hi!

I have discovered an issue with the current etcd URL setup in the kube-apiserver job.
When using collocated etcd and specifying every URL for etcd, kubernetes API
stops responding if one of the etcd nodes goes down. The problem can be mitigated
by specifying `127.0.0.1` as the etcd address, as recommended by the [Google guide](https://kubernetes.io/docs/admin/high-availability/kube-apiserver.yaml).

Test scenario:
Deploy a cfcr cluster with three master nodes using an outdated stemcell.
Start the stemcell update process. Try to call `kubectl get all` command,
it will sometimes get frozen for long periods of time.

**Comment by tvs** [comment] 2018-05-02 23:43
After the various fixes related to multi-master and etcd aliases, I'm not seeing this happen when etcd goes down.

Steps:
1. Deployed 3 Master, 3 Worker cluster.
2. Set a `watch kubectl get all --all-namespaces` in one (local) terminal.
3. SSH'd into `master/0` and stopped etcd: `monit stop etcd`
   * Confirmed via `ps`
4. Observed no API failures in the watch and ran the same `kubectl get all --all-namespaces` on `master/0` repeatedly without issue.

I'm also not sure what we could do about this with the [recent discovery regarding certificates and SANs in etcd](https://www.pivotaltracker.com/story/show/157092708/comments/188933350). The short version is that by connecting over `localhost`/`127.0.0.1` the certs need to have a SAN for `localhost`/`127.0.0.1`, but by adding a SAN, etcd does a second round of certificate validation that doesn't seem to play nicely with bosh-dns (it's unable to resolve the IP address to the alias and therefore rejects inbound connections).

I'm also not entirely convinced that we _should_ be connecting through `localhost`/`127.0.0.1`: https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd#multi-node-etcd-cluster

In the [High Availability docs](https://kubernetes.io/docs/admin/high-availability/building), the API server and etcd are being self-hosted, which is similar to being colocated, but not identical (they also use a discovery token the bootstrap the etcd cluster, among other things). They also only connect to a single etcd instance rather than the full list as suggested in the other doc. That's something I've gone ahead and tried out, but if anything, its only served to make the node more brittle (once etcd goes down, that apiserver ceases to respond and `kubectl` will simply hang).

-----------------

What I _can_ see happen during upgrade is that occasionally a request to the load balancer appears to fail partially. Presumably because it's hitting the master node that's rolling through an upgrade and `kube-apiserver`/`etcd` are in some unknown/initial state. When this happens, the pods listing fails, though other elements do show:

```
$ kubectl get all --all-namespaces
NAMESPACE     NAME                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)         AGE
default       kubernetes             ClusterIP   10.100.200.1     <none>        443/TCP         16m
kube-system   heapster               ClusterIP   10.100.200.37    <none>        8443/TCP        5m
kube-system   kube-dns               ClusterIP   10.100.200.10    <none>        53/UDP,53/TCP   5m
kube-system   kubernetes-dashboard   NodePort    10.100.200.139   <none>        443:30324/TCP   5m
kube-system   monitoring-influxdb    ClusterIP   10.100.200.123   <none>        8086/TCP        5m

NAMESPACE     NAME                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   heapster               1         1         1            1           5m
kube-system   kube-dns               1         1         1            1           5m
kube-system   kubernetes-dashboard   1         1         1            1           5m
kube-system   monitoring-influxdb    1         1         1            1           5m

NAMESPACE     NAME                              DESIRED   CURRENT   READY     AGE
kube-system   heapster-7cf4bfcf                 1         1         1         5m
kube-system   kube-dns-b84b46b5                 1         1         1         5m
kube-system   kubernetes-dashboard-6bc7f5856b   1         1         1         5m
kube-system   monitoring-influxdb-bc594c557     1         1         1         5m
The connection to the server <Loadbalancer IP>:8443 was refused - did you specify the right host or port?
```

The missing chunk:

```
NAMESPACE     NAME                                    READY     STATUS    RESTARTS   AGE
kube-system   heapster-7cf4bfcf-7tpj4                 1/1       Running   0          5m
kube-system   kube-dns-b84b46b5-lfs4m                 3/3       Running   0          5m
kube-system   kubernetes-dashboard-6bc7f5856b-9lqqw   1/1       Running   0          5m
kube-system   monitoring-influxdb-bc594c557-vnz4t     1/1       Running   0          5m
```

Just to track down what's happening:

```
$ kubectl get all --all-namespaces -v 8 |& tee output.txt
...
I0501 18:10:13.960195   43323 round_trippers.go:383] GET https://<Loadbalancer IP>:8443/api/v1/pods?limit=500
I0501 18:10:13.960207   43323 round_trippers.go:390] Request Headers:
I0501 18:10:13.960211   43323 round_trippers.go:393]     Accept: application/json
I0501 18:10:13.960216   43323 round_trippers.go:393]     User-Agent: kubectl/v1.10.0 (darwin/amd64) kubernetes/fc32d2f
I0501 18:10:13.960221   43323 round_trippers.go:393]     Authorization: Bearer lHtzW81QaCNWH1JBZ2wGyJVfuMQdU5
I0501 18:10:14.023575   43323 round_trippers.go:408] Response Status:  in 63 milliseconds
...
```

The `GET pods` request is the first in the line, so I think that the load balancer issues the request to our upgrading node, recognizes that there's nothing there to respond successfully, and then points all of the remaining requests (`replicationcontrollers`, `services`, `daemonsets`, `deployments`, `replicasets`, `statefulsets`, `horizontalpodautoscalers`, `jobs`, and `cronjobs`) to a working node. Sometime later (assuming the upgrade hasn't completed), the load balancer will retry that node.

This is pretty easy to replicate by simply SSHing onto `master/0` and issuing `monit stop kube-apiserver` before going back to `kubectl`. I'm not sure that this is anything we can aim to fix, and I'm skeptical that there's any change we could make to the way `kube-apiserver` talks with `etcd` that would address it.

**Comment by tvs** [comment] 2018-05-03 16:49
CI will soon have tests that cover API uptime during upgrades (both CFCR and stemcell). If this is still a problem and I was just lucky during my testing, it'll likely get caught there.

We'll go ahead and re-open and rename this issue if it crops back up. In the meanwhile, I'll go ahead and close it out. Thanks!

**Closed by tvs** 2018-05-03 16:49 UTC
Labels: in progress
