### ISSUE TITLE
Drain script failing in 0.16.0

### ISSUE THREAD

**Issue by bstick12** [cloudfoundry-incubator/kubo-release#198] opened 2018-04-23 14:12 UTC
Deletion of cluster fails. 

Task 81 | 13:47:49 | Deleting instances: worker/cb321afb-bd46-4e42-812c-ab5201b0b2e7 (0) (00:00:04)
                   L Error: Action Failed get_task: Task 6bb0a279-f509-4dd5-59d5-5b6e05154003 result: 1 of 1 drain scripts failed. Failed Jobs: kubelet.

It looks like a race condition where the master disappears during the deletion of the node by the drain script. Causing the `trap ensure_safe_exit EXIT` with a non zero exit code.  

drain.stderr.log
```
WARNING: Deleting pods with local storage: kubernetes-dashboard-6fd599dd98-8b7zx, monitoring-influxdb-744b677649-qdnpd
The connection to the server master.cfcr.internal:8443 was refused - did you specify the right host or port?
```

drain.stdout.log
```
node "vm-93d5e1dd-0fc8-46a6-7398-77b62e98cb40" cordoned
pod "monitoring-influxdb-744b677649-qdnpd" evicted
pod "frontend-67f65745c-jfpt4" evicted
pod "frontend-67f65745c-n8cmd" evicted
pod "kubernetes-dashboard-6fd599dd98-8b7zx" evicted
pod "redis-master-7747787588-r85ms" evicted
pod "heapster-78dbf7db87-db8l7" evicted
pod "redis-slave-865486c9df-ttprf" evicted
node "vm-93d5e1dd-0fc8-46a6-7398-77b62e98cb40" drained
Kubelet drain failed
```

**Comment by iainsproat** [comment] 2018-04-23 14:55
Thanks @bstick12 - @alex-slynko reported something similar which we're working on, please refer to https://www.pivotaltracker.com/story/show/156658555

**Comment by tvs** [comment] 2018-04-24 18:12
The issue being tracked in [story 156658555](https://www.pivotaltracker.com/story/show/156658555) is specifically about multi-master deletion.

The issue mentioned here, I've also seen happen in single-master deployments and is just dependent on when the master is deleted relative to the workers. I pushed a fix for this specific issue the other day, wrapping both the `drain` and `delete` steps in the `fail_if_master_is_running` logic: https://github.com/cloudfoundry-incubator/kubo-release/commit/79b6618203e8d5c734125dfbdcf723a489911d8a

That _should_ allow the node delete to fail silently if the master is going down. It's hard to get the problem to reproduce consistently, however, so there may still be complications in draining. This also doesn't really do anything for the multi-master deletion scenario (where the `drain` or `delete` fails because the specific master they were issued to is going down). If we can get BOSH to set some indication for _why_ the drain is being called (e.g. `delete-deployment` vs `scale`), we'll be able to fix both of these issues in a cleaner way.

I'm going to go ahead and close this since we think we already have a solution for this specific problem. Please re-open it if you see it happening with the latest builds off master (or in the next release).

**Closed by tvs** 2018-04-24 18:12 UTC
Labels: in progress
