### ISSUE TITLE
v0.9.0 missing from releases/

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/kubo-release#131] opened 2017-11-25 04:14 UTC
In https://github.com/cloudfoundry-incubator/kubo-release/releases there is v0.9.0 (and thanks for including the tgz file); but the final release files are missing from https://github.com/cloudfoundry-incubator/kubo-release/tree/master/releases/kubo

This prevents operators for using the following to specify v0.9.0:

```
releases:
- name: kubo
  version: 0.9.9
  url: git+https://github.com/cloudfoundry-incubator/kubo-release
```

**Comment by jhvhs** [comment] 2017-11-27 10:11
Thank you @drnic . The issue is now fixed.

**Closed by jhvhs** 2017-11-27 10:11 UTC
Labels: unscheduled
